#Banco 

#Criando a imagem a partir da imagem do postgres
FROM postgres
#Definindo o nome do banco
ENV POSTGRES_DB=Teste
#Definindo o usuário
ENV POSTGRES_USER=ads
#Definindo a senha do usuário
ENV POSTGRES_PASSWORD=123456